#!/bin/bash

set -e

cd "$(dirname "$0")"

ACCOUNT=0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f
RPCAPI="eth,net,web3,admin,personal,debug"
GETHNETDIR=./datadir

# Enable different gethnet subcommands such as clean or console.
# No subcommand runs the main mining geth.
case "$1" in
  attach)
    geth attach ws://localhost:18546
    ;;
  clean)
    rm -rf $GETHNETDIR
    ;;
  console)
    geth console --dev --mine --networkid 17 --wsorigins "*" --rpc --ws \
      --rpcapi "$RPCAPI" --rpccorsdomain "null" \
      --rpcaddr 127.0.0.1 --rpcport 18545 --wsport 18546 --datadir $GETHNETDIR \
      --unlock "$ACCOUNT" \
      --ipcdisable \
      --password ../clroot/password.txt
    ;;
  *)
    geth --dev --mine --networkid 17 --wsorigins "*" --rpc --ws \
      --rpcapi "$RPCAPI" --rpccorsdomain "null" \
      --rpcaddr 127.0.0.1 --dev.period 2 --rpcport 18545 --wsport 18546 \
      --datadir $GETHNETDIR \
      --unlock "$ACCOUNT" \
      --ipcdisable \
      --password ./password.txt \
      --verbosity 1
    ;;
esac
